// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA3DG_EK29rAyQRCCNvnFEGrppJP-GF9g',
    appId: '1:98649011712:web:45c28fa981644b0f79cae5',
    messagingSenderId: '98649011712',
    projectId: 'ordersapp-fa9d6',
    authDomain: 'ordersapp-fa9d6.firebaseapp.com',
    storageBucket: 'ordersapp-fa9d6.firebasestorage.app',
    measurementId: 'G-7RRZXPTC9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASG4dRcNvndCxGl7LgBVB8B7a8CA1GtK0',
    appId: '1:98649011712:android:fbf47265df24f78c79cae5',
    messagingSenderId: '98649011712',
    projectId: 'ordersapp-fa9d6',
    storageBucket: 'ordersapp-fa9d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtcN3OdbO5jjyshmeuG8Yk05OxbNw4UCk',
    appId: '1:98649011712:ios:cc869bf9d223157479cae5',
    messagingSenderId: '98649011712',
    projectId: 'ordersapp-fa9d6',
    storageBucket: 'ordersapp-fa9d6.firebasestorage.app',
    iosClientId: '98649011712-vge49vqmbr8gr74r6jldtdksk9s32l4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.butterflyV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtcN3OdbO5jjyshmeuG8Yk05OxbNw4UCk',
    appId: '1:98649011712:ios:cc869bf9d223157479cae5',
    messagingSenderId: '98649011712',
    projectId: 'ordersapp-fa9d6',
    storageBucket: 'ordersapp-fa9d6.firebasestorage.app',
    iosClientId: '98649011712-vge49vqmbr8gr74r6jldtdksk9s32l4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.butterflyV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA3DG_EK29rAyQRCCNvnFEGrppJP-GF9g',
    appId: '1:98649011712:web:0fd175d7870b857679cae5',
    messagingSenderId: '98649011712',
    projectId: 'ordersapp-fa9d6',
    authDomain: 'ordersapp-fa9d6.firebaseapp.com',
    storageBucket: 'ordersapp-fa9d6.firebasestorage.app',
    measurementId: 'G-V5W8T7YNS5',
  );
}
